development:
  adapter: postgresql
  encoding: unicode
  database: video_glance_development
  pool: 5
  username: tomohung
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: video_glance_test
  pool: 5
  username: tomohung
  password: 
